FROM jenkins/jenkins:lts

USER root

# Install Node.js + npm + yarn
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get install -y nodejs \
  && npm install -g yarn

USER jenkins
